/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  AddressBanList,
  AddressBanListInterface,
} from "../AddressBanList";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "isBanned",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class AddressBanList__factory {
  static readonly abi = _abi;
  static createInterface(): AddressBanListInterface {
    return new utils.Interface(_abi) as AddressBanListInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): AddressBanList {
    return new Contract(address, _abi, signerOrProvider) as AddressBanList;
  }
}
