/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { BanList, BanListInterface } from "../BanList";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "isBanned",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class BanList__factory {
  static readonly abi = _abi;
  static createInterface(): BanListInterface {
    return new utils.Interface(_abi) as BanListInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): BanList {
    return new Contract(address, _abi, signerOrProvider) as BanList;
  }
}
