/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IGuildPayDistribution,
  IGuildPayDistributionInterface,
} from "../IGuildPayDistribution";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
    ],
    name: "balanceOfAll",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "guildTokenAmount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "bmonAmount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "bmonZ2Amount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "bnbAmount",
            type: "uint256",
          },
        ],
        internalType: "struct UserTokenBalance",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
    ],
    name: "balanceOfBMON",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
    ],
    name: "balanceOfBNB",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
    ],
    name: "balanceOfGT",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
    ],
    name: "balanceOfZ2",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_centralPayment",
        type: "address",
      },
      {
        internalType: "address",
        name: "_guildOwner",
        type: "address",
      },
      {
        internalType: "address",
        name: "_parentA",
        type: "address",
      },
      {
        internalType: "address",
        name: "_parentB",
        type: "address",
      },
      {
        internalType: "address",
        name: "_referral",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "breedFee",
        type: "uint256",
      },
    ],
    name: "distributeForBreedFee",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IGuildPayDistribution__factory {
  static readonly abi = _abi;
  static createInterface(): IGuildPayDistributionInterface {
    return new utils.Interface(_abi) as IGuildPayDistributionInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IGuildPayDistribution {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IGuildPayDistribution;
  }
}
