/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface ErrorsInterface extends utils.Interface {
  contractName: "Errors";
  functions: {
    "GC_FORBIDDEN()": FunctionFragment;
    "GF_ALREADY_SUBSCRIBED()": FunctionFragment;
    "GF_DUPLICATE_GUILD_NAME()": FunctionFragment;
    "GF_DUPLICATE_GUILD_SYMBOL()": FunctionFragment;
    "GF_NOT_ENOUGH_MIN_BMON_LOCKING()": FunctionFragment;
    "GF_NOT_ENOUGH_YOUR_BALANCE()": FunctionFragment;
    "GF_NOT_OWNED_GENESIS_MONSTER()": FunctionFragment;
    "GF_NOT_OWNED_LAND()": FunctionFragment;
    "GF_OWNER_MONSTER_AMOUNT()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "GC_FORBIDDEN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GF_ALREADY_SUBSCRIBED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GF_DUPLICATE_GUILD_NAME",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GF_DUPLICATE_GUILD_SYMBOL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GF_NOT_ENOUGH_MIN_BMON_LOCKING",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GF_NOT_ENOUGH_YOUR_BALANCE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GF_NOT_OWNED_GENESIS_MONSTER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GF_NOT_OWNED_LAND",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GF_OWNER_MONSTER_AMOUNT",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "GC_FORBIDDEN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GF_ALREADY_SUBSCRIBED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GF_DUPLICATE_GUILD_NAME",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GF_DUPLICATE_GUILD_SYMBOL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GF_NOT_ENOUGH_MIN_BMON_LOCKING",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GF_NOT_ENOUGH_YOUR_BALANCE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GF_NOT_OWNED_GENESIS_MONSTER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GF_NOT_OWNED_LAND",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GF_OWNER_MONSTER_AMOUNT",
    data: BytesLike
  ): Result;

  events: {};
}

export interface Errors extends BaseContract {
  contractName: "Errors";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ErrorsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    GC_FORBIDDEN(overrides?: CallOverrides): Promise<[string]>;

    GF_ALREADY_SUBSCRIBED(overrides?: CallOverrides): Promise<[string]>;

    GF_DUPLICATE_GUILD_NAME(overrides?: CallOverrides): Promise<[string]>;

    GF_DUPLICATE_GUILD_SYMBOL(overrides?: CallOverrides): Promise<[string]>;

    GF_NOT_ENOUGH_MIN_BMON_LOCKING(
      overrides?: CallOverrides
    ): Promise<[string]>;

    GF_NOT_ENOUGH_YOUR_BALANCE(overrides?: CallOverrides): Promise<[string]>;

    GF_NOT_OWNED_GENESIS_MONSTER(overrides?: CallOverrides): Promise<[string]>;

    GF_NOT_OWNED_LAND(overrides?: CallOverrides): Promise<[string]>;

    GF_OWNER_MONSTER_AMOUNT(overrides?: CallOverrides): Promise<[string]>;
  };

  GC_FORBIDDEN(overrides?: CallOverrides): Promise<string>;

  GF_ALREADY_SUBSCRIBED(overrides?: CallOverrides): Promise<string>;

  GF_DUPLICATE_GUILD_NAME(overrides?: CallOverrides): Promise<string>;

  GF_DUPLICATE_GUILD_SYMBOL(overrides?: CallOverrides): Promise<string>;

  GF_NOT_ENOUGH_MIN_BMON_LOCKING(overrides?: CallOverrides): Promise<string>;

  GF_NOT_ENOUGH_YOUR_BALANCE(overrides?: CallOverrides): Promise<string>;

  GF_NOT_OWNED_GENESIS_MONSTER(overrides?: CallOverrides): Promise<string>;

  GF_NOT_OWNED_LAND(overrides?: CallOverrides): Promise<string>;

  GF_OWNER_MONSTER_AMOUNT(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    GC_FORBIDDEN(overrides?: CallOverrides): Promise<string>;

    GF_ALREADY_SUBSCRIBED(overrides?: CallOverrides): Promise<string>;

    GF_DUPLICATE_GUILD_NAME(overrides?: CallOverrides): Promise<string>;

    GF_DUPLICATE_GUILD_SYMBOL(overrides?: CallOverrides): Promise<string>;

    GF_NOT_ENOUGH_MIN_BMON_LOCKING(overrides?: CallOverrides): Promise<string>;

    GF_NOT_ENOUGH_YOUR_BALANCE(overrides?: CallOverrides): Promise<string>;

    GF_NOT_OWNED_GENESIS_MONSTER(overrides?: CallOverrides): Promise<string>;

    GF_NOT_OWNED_LAND(overrides?: CallOverrides): Promise<string>;

    GF_OWNER_MONSTER_AMOUNT(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    GC_FORBIDDEN(overrides?: CallOverrides): Promise<BigNumber>;

    GF_ALREADY_SUBSCRIBED(overrides?: CallOverrides): Promise<BigNumber>;

    GF_DUPLICATE_GUILD_NAME(overrides?: CallOverrides): Promise<BigNumber>;

    GF_DUPLICATE_GUILD_SYMBOL(overrides?: CallOverrides): Promise<BigNumber>;

    GF_NOT_ENOUGH_MIN_BMON_LOCKING(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    GF_NOT_ENOUGH_YOUR_BALANCE(overrides?: CallOverrides): Promise<BigNumber>;

    GF_NOT_OWNED_GENESIS_MONSTER(overrides?: CallOverrides): Promise<BigNumber>;

    GF_NOT_OWNED_LAND(overrides?: CallOverrides): Promise<BigNumber>;

    GF_OWNER_MONSTER_AMOUNT(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    GC_FORBIDDEN(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    GF_ALREADY_SUBSCRIBED(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    GF_DUPLICATE_GUILD_NAME(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    GF_DUPLICATE_GUILD_SYMBOL(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    GF_NOT_ENOUGH_MIN_BMON_LOCKING(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    GF_NOT_ENOUGH_YOUR_BALANCE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    GF_NOT_OWNED_GENESIS_MONSTER(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    GF_NOT_OWNED_LAND(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    GF_OWNER_MONSTER_AMOUNT(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
