/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "CentralPayment",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CentralPayment__factory>;
    getContractFactory(
      name: "AddressBanList",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AddressBanList__factory>;
    getContractFactory(
      name: "BanList",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BanList__factory>;
    getContractFactory(
      name: "BinamonCollectionV2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BinamonCollectionV2__factory>;
    getContractFactory(
      name: "BinamonEnergy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BinamonEnergy__factory>;
    getContractFactory(
      name: "BinamonGenesis",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BinamonGenesis__factory>;
    getContractFactory(
      name: "BinamonLand",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BinamonLand__factory>;
    getContractFactory(
      name: "BinamonZ1",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BinamonZ1__factory>;
    getContractFactory(
      name: "CollectionTypeMover",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CollectionTypeMover__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "IERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721__factory>;
    getContractFactory(
      name: "IERC721Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Metadata__factory>;
    getContractFactory(
      name: "LegacyCollection",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LegacyCollection__factory>;
    getContractFactory(
      name: "Pausable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Pausable__factory>;
    getContractFactory(
      name: "Trustable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Trustable__factory>;
    getContractFactory(
      name: "IBinamonCollectionV2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IBinamonCollectionV2__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "IERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721__factory>;
    getContractFactory(
      name: "IGuildFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IGuildFactory__factory>;
    getContractFactory(
      name: "IGuildPayDistribution",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IGuildPayDistribution__factory>;
    getContractFactory(
      name: "IUniswapV2Pair",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IUniswapV2Pair__factory>;
    getContractFactory(
      name: "Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Errors__factory>;
    getContractFactory(
      name: "Trustable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Trustable__factory>;
    getContractFactory(
      name: "GuildCore",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.GuildCore__factory>;
    getContractFactory(
      name: "GuildFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.GuildFactory__factory>;
    getContractFactory(
      name: "GuildPayDistribution",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.GuildPayDistribution__factory>;
    getContractFactory(
      name: "BMONZ1",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BMONZ1__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "BMONZ2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BMONZ2__factory>;
    getContractFactory(
      name: "BMON",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BMON__factory>;
    getContractFactory(
      name: "BMONSeedAndPreSale",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BMONSeedAndPreSale__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "GuildToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.GuildToken__factory>;

    getContractAt(
      name: "CentralPayment",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.CentralPayment>;
    getContractAt(
      name: "AddressBanList",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AddressBanList>;
    getContractAt(
      name: "BanList",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.BanList>;
    getContractAt(
      name: "BinamonCollectionV2",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.BinamonCollectionV2>;
    getContractAt(
      name: "BinamonEnergy",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.BinamonEnergy>;
    getContractAt(
      name: "BinamonGenesis",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.BinamonGenesis>;
    getContractAt(
      name: "BinamonLand",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.BinamonLand>;
    getContractAt(
      name: "BinamonZ1",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.BinamonZ1>;
    getContractAt(
      name: "CollectionTypeMover",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.CollectionTypeMover>;
    getContractAt(
      name: "IERC165",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "IERC721",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721>;
    getContractAt(
      name: "IERC721Metadata",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Metadata>;
    getContractAt(
      name: "LegacyCollection",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.LegacyCollection>;
    getContractAt(
      name: "Pausable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Pausable>;
    getContractAt(
      name: "Trustable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Trustable>;
    getContractAt(
      name: "IBinamonCollectionV2",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IBinamonCollectionV2>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "IERC165",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "IERC721",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721>;
    getContractAt(
      name: "IGuildFactory",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IGuildFactory>;
    getContractAt(
      name: "IGuildPayDistribution",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IGuildPayDistribution>;
    getContractAt(
      name: "IUniswapV2Pair",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IUniswapV2Pair>;
    getContractAt(
      name: "Errors",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Errors>;
    getContractAt(
      name: "Trustable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Trustable>;
    getContractAt(
      name: "GuildCore",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.GuildCore>;
    getContractAt(
      name: "GuildFactory",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.GuildFactory>;
    getContractAt(
      name: "GuildPayDistribution",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.GuildPayDistribution>;
    getContractAt(
      name: "BMONZ1",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.BMONZ1>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "BMONZ2",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.BMONZ2>;
    getContractAt(
      name: "BMON",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.BMON>;
    getContractAt(
      name: "BMONSeedAndPreSale",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.BMONSeedAndPreSale>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "GuildToken",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.GuildToken>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
